import type { Config } from "tailwindcss";
import forms from "@tailwindcss/forms";

const config: Config = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container": "#eceef0",
        "inverse-on-surface": "#eff1f3",
        "surface-dim": "#d8dadc",
        "on-tertiary-fixed": "#0d1c2f",
        "primary-container": "#0a1f44",
        "on-secondary-fixed": "#3a0a00",
        "surface-tint": "#4c5e86",
        "on-primary": "#ffffff",
        "on-tertiary-container": "#7a899f",
        "secondary-fixed": "#ffdbd0",
        "surface-container-low": "#f2f4f6",
        "on-tertiary-fixed-variant": "#3a485c",
        "inverse-surface": "#2d3133",
        "on-secondary-fixed-variant": "#852400",
        "on-primary-fixed": "#041a3f",
        "on-surface": "#191c1e",
        "outline-variant": "#c5c6cf",
        "primary-fixed-dim": "#b4c6f4",
        background: "#f7f9fb",
        "on-primary-fixed-variant": "#34466d",
        "on-surface-variant": "#44464e",
        "on-error-container": "#93000a",
        "surface-bright": "#f7f9fb",
        "on-secondary-container": "#5b1500",
        outline: "#75777f",
        secondary: "#ae3100",
        "surface-container-highest": "#e0e3e5",
        "surface-variant": "#e0e3e5",
        "secondary-container": "#fe6431",
        "on-background": "#191c1e",
        "on-primary-container": "#7687b2",
        error: "#ba1a1a",
        "surface-container-high": "#e6e8ea",
        "on-error": "#ffffff",
        "primary-fixed": "#d9e2ff",
        primary: "#00081e",
        "error-container": "#ffdad6",
        "tertiary-container": "#122134",
        "inverse-primary": "#b4c6f4",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#b9c7e0",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#ffb59f",
        "tertiary-fixed": "#d5e3fd",
        tertiary: "#000919",
        surface: "#f7f9fb",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "margin-desktop": "48px",
        base: "8px",
        gutter: "24px",
        "margin-mobile": "16px",
        "container-max": "1280px",
      },
      maxWidth: {
        "container-max": "1280px",
      },
      fontFamily: {
        "headline-lg-mobile": ["var(--font-inter)"],
        "headline-lg": ["var(--font-inter)"],
        "display-lg": ["var(--font-inter)"],
        "body-md": ["var(--font-inter)"],
        "body-lg": ["var(--font-inter)"],
        "label-sm": ["var(--font-inter)"],
        "title-md": ["var(--font-inter)"],
        "label-md": ["var(--font-inter)"],
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "title-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [forms],
};

export default config;
